[package]
name = "flash_backup"
version = "0.1.0"
authors = ["szymon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
