[package]
name = "flash_backup"
version = "0.1.0"
authors = ["szymon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
serde = {version = "1.0.104", features = ["derive"]}
serde_json = "1.0"
sha-1 = "0.8.2"
hex = "0.4.2"
blake3 = "0.2.2"